# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"

  config.vm.define "keycloak-1" do |k|
    k.vm.provision "ansible" do |ansible|
      ansible.playbook = "prepare.yml"
      ansible.limit = "keycloak"
      ansible.groups = {
        "keycloak" => ["keycloak-1"],
      }
      ansible.extra_vars = {
        "keycloak_db_name": "keycloak",
        "keycloak_db_username": "keycloak",
        "keycloak_db_password": "abc123",
        "keycloak_user": "root",
        "keycloak_group": "root",
        "keycloak_no_log": FALSE,
      }
    end

    k.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
      ansible.limit = "keycloak"
      ansible.groups = {
        "keycloak" => ["keycloak-1"],
      }
      ansible.extra_vars = {
        "keycloak_start_args": "start-dev",
        "keycloak_db_name": "keycloak",
        "keycloak_db_username": "keycloak",
        "keycloak_db_password": "abc123",
        "keycloak_config": [
          { "name": "https-certificate-file", "state": "absent" },
          { "name": "https-certificate-key-file", "state": "absent" },
          { "name": "proxy", "state": "absent" },
          { "name": "spi-sticky-session-encoder-infinispan-should-attach-route", "state": "absent" },
          { "name": "hostname", "value": "{{ ansible_default_ipv4.address }}" },
        ],
        "keycloak_user": "root",
        "keycloak_group": "root",
        "keycloak_no_log": FALSE,
      }
    end
  end
end
