---
# handlers file for keycloak
- name: Handle keycloak changes
  when:
    - "keycloak_service_name is not none"
    - "keycloak_handler_service_state is not none"
    - "'molecule-converge-test' not in ansible_run_tags"
  listen:
    - reload keycloak
  tags:
    - keycloak
  ansible.builtin.service:
    name: "{{ keycloak_service_name }}"
    state: "{{ keycloak_handler_service_state }}"
